"""add_projects_and_material_chunks

Revision ID: 003a121bfe74
Revises: e6b27f198c07
Create Date: 2026-02-27 18:33:52.735589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '003a121bfe74'
down_revision: Union[str, None] = 'e6b27f198c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Projects
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
    )

    op.execute("""
        INSERT INTO projects (id, owner_id, title, created_at)
        SELECT gen_random_uuid(), u.id, 'Default project', now()
        FROM users u
        WHERE NOT EXISTS (
            SELECT 1 FROM projects p WHERE p.owner_id = u.id
        );
    """)

    # Material chunks
    op.create_table(
        "material_chunks",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(3072), nullable=False),
        sa.Column("page", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="CASCADE"),
    )

    op.create_index(
        "ix_material_chunks_project_id",
        "material_chunks",
        ["project_id"],
    )
    op.create_index(
        "ix_material_chunks_material_id",
        "material_chunks",
        ["material_id"],
    )

    # Связь materials → projects
    op.add_column(
        "materials",
        sa.Column("project_id", sa.UUID(), nullable=True),
    )
    op.execute("""
        UPDATE materials m
        SET project_id = p.id
        FROM projects p
        WHERE p.owner_id = m.user_id
        AND m.project_id IS NULL;
    """)
    op.alter_column(
        "materials",
        "project_id",
        nullable=False,
    )
    op.create_foreign_key(
        "fk_materials_project",
        "materials",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_materials_project",
        "materials",
        type_="foreignkey",
    )
    op.drop_column("materials", "project_id")

    # удалить индексы material_chunks
    op.drop_index("ix_material_chunks_material_id", table_name="material_chunks")
    op.drop_index("ix_material_chunks_project_id", table_name="material_chunks")

    # удалить таблицы
    op.drop_table("material_chunks")
    op.drop_table("projects")
    # ### end Alembic commands ###
