"""increase_presentation_url_column_size

Revision ID: 69f9387fe939
Revises: 8ff1e48b75ed
Create Date: 2025-12-22 20:12:28.927977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f9387fe939'
down_revision: Union[str, None] = '8ff1e48b75ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'presentation_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('materials', 'presentation_embed_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'presentation_embed_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('materials', 'presentation_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
